---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tomcat
  namespace: default
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: "ashwin198/myweb"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: default
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80